added 85% minimum code coverage test

diff --git a/.github/workflows/pull-request_validation.yml b/.github/workflows/pull-request_validation.yml
--- a/.github/workflows/pull-request_validation.yml
+++ b/.github/workflows/pull-request_validation.yml
@@ -72,9 +72,19 @@ jobs:
           echo "::set-output name=classes::$( echo $classes | sed 's/\(.*\),/\1 /' )"
 
       # Run Apex tests in scratch org
-      # TODO throw error on below 75% code coverage
       - name: "Run Apex tests"
         run: "sfdx force:apex:test:run -t ${{ steps.test-classes-in-repo.outputs.classes }} -c -r human -d ./tests/apex -w 20"
+
+      # Validate at least 85% code coverage
+      - name: Validate at least 85% code coverage
+        run:
+          codecoverage=$(cat tests/apex/test-result-7*.json | jq '.summary.testRunCoverage' | sed 's/\"//g; s/\%//g')
+          if [ $codecoverage -lt 85 ]
+          then
+            echo "Code coverage: $codecoverage%"
+            echo "Because it is less than 85%, the validation failed"
+            exit 125
+          fi
 
       # Delete scratch orgs
       - name: "Delete scratch org"
